import type { AgentConfig, AgentKey, RecommendationBlock } from "./types";

export const DEMO_CONFIG = {
  settings: {
    defaultAgent: "codex" as AgentKey,
    autoplay: true,
    intersectionThreshold: 0.35,
    speed: 1.2,
    userTypingMultiplier: 1.8,
  },
  section: {
    eyebrow: "Demo",
    title: "Your agent gets better\nafter every run.",
    summary:
      "Penelopa turns real Codex and Claude Code work into reusable skills, checks, and prompts your agent can apply next time.",
  },
  labels: {
    phaseFormat: "{index} / {label}",
    workspaceConnected: "Workspace connected",
    explorer: "Explorer",
    repositoryContext: "Repository context enabled",
    copy: "Copy recommendation",
    copied: "Copied",
    copyToast: "Copied for your agent",
    complete: "Improvement applied",
    replay: "Replay demo",
    dashboard: "Dashboard",
  },
  brand: {
    name: "Penelopa.ai",
    logoUrl: "/penelopa-ai.png",
  },
  project: {
    name: "weather-dashboard",
    branch: "main",
    files: [
      { name: "src", kind: "folder", depth: 0 },
      { name: "weather", kind: "folder", depth: 1 },
      { name: "parser.ts", kind: "file", depth: 2, active: true },
      { name: "fixtures.ts", kind: "file", depth: 2 },
      { name: "components", kind: "folder", depth: 1 },
      { name: "WeatherCard.tsx", kind: "file", depth: 2 },
      { name: "tests/weather-parser.test.ts", kind: "file", depth: 0 },
      { name: "scripts", kind: "folder", depth: 0 },
    ],
  },
  analysis: {
    eyebrow: "Penelopa.ai / Auto-improve",
    tokens: [
      "forecast parser",
      "unit conversion",
      "missing temp",
      "empty rain",
      "timezone label",
      "fixture gap",
      "WeatherCard",
      "same check again",
      "session #05",
      "session #09",
      "validation pattern",
      "skill candidate",
    ],
    stages: [
      {
        title: "Spotting the repeated work.",
        copy: "Penelopa reads how the agent checks weather API responses, fixes edge cases and tests the forecast card.",
        status: "Reviewing session",
        duration: 1200,
      },
      {
        title: "Finding the reusable step.",
        copy: "The same checks appear across weather dashboard tasks: missing temperatures, mixed units, empty rain and timezone drift.",
        status: "Detecting pattern",
        duration: 1400,
      },
      {
        title: "Turning it into a skill.",
        copy: "Penelopa packages those checks into a short validation workflow your agent can reuse before changing weather code.",
        status: "Drafting improvement",
        duration: 1500,
      },
    ],
    resolveDuration: 900,
  },
  recommendation: {
    eyebrow: "Recommendation",
    title: "Create a weather data validation skill",
    metadata: [
      "WEATHER-DASHBOARD",
      "9 SESSIONS",
      "04 SEP 2026",
      "IMPROVEMENT / SKILL + CHECKS",
    ],
    copyExcerpt:
      "Create a reusable weather data validation skill. It should check units, missing temperatures, empty precipitation, timezone labels and API fixture coverage before a weather UI change is considered complete.",
    report: [
      {
        type: "heading",
        level: 2,
        text: "Observed pattern",
      },
      {
        type: "paragraph",
        text: "Across 9 coding sessions, the agent kept rediscovering the same weather API checks before updating the dashboard: normalize Celsius and Fahrenheit, guard missing temperatures, handle empty precipitation, label local time correctly and run the forecast-card fixture tests.",
      },
      {
        type: "quote",
        text: "The agent is doing the right checks, but it has to remember them from scratch every time.",
      },
      {
        type: "heading",
        level: 2,
        text: "Recommended intervention",
      },
      {
        type: "list",
        items: [
          "Add a project skill at .codex/skills/weather-data-validation/SKILL.md with the canonical weather data checks.",
          "Add scripts/check_weather_data.ts to validate API fixtures, unit conversion and missing-value fallbacks.",
          "Make the forecast-card fixture tests part of the skill's completion criteria, not an optional follow-up.",
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Expected result",
      },
      {
        type: "paragraph",
        text: "Future agents start with a ready weather checklist instead of rediscovering it. Fixes get smaller, forecast cards stay readable and every completed task leaves the next one easier.",
      },
      {
        type: "heading",
        level: 3,
        text: "Suggested invocation",
      },
      {
        type: "paragraph",
        text: "Run `npm test -- weather-parser.test.ts`, then check the London, Phoenix and rainy-day fixtures before presenting the final answer.",
      },
    ] satisfies RecommendationBlock[],
  },
  agents: {
    codex: {
      label: "Codex",
      mark: "C",
      model: "GPT-5.6 Codex",
      composerPlaceholder: "Ask Codex to follow up",
      accentLight: "#516a57",
      accentDark: "#abc5b1",
      flow: [
        {
          type: "phase",
          index: "01",
          label: "Session",
          progress: 0.03,
          hold: 250,
        },
        {
          type: "compose",
          mode: "type",
          text: "The weather card shows 72°C for Phoenix and leaves the rain value blank. Trace the parser and make the smallest safe fix.",
          duration: 1100,
          hold: 180,
        },
        {
          type: "send",
          label: "You",
          hold: 520,
        },
        {
          type: "reasoning",
          label: "Reasoning",
          text: "I will check the weather API shape and parser tests first, then normalize only the units and empty rain fallback.",
          duration: 1050,
          hold: 260,
        },
        {
          type: "tool",
          name: "rg",
          input: 'rg "temperature|unit|precipitation|forecast" src tests -n',
          result:
            "src/weather/parser.ts:42  temperature = reading.temp\nsrc/weather/parser.ts:58  precipitationMm = reading.rain\nsrc/components/WeatherCard.tsx:31  formatTemperature(...)",
          duration: 950,
          hold: 220,
        },
        {
          type: "tool",
          name: "read_file",
          input: "src/weather/parser.ts:34-78",
          result:
            "The parser trusts the provider unit flag and renders missing rain values directly.",
          duration: 900,
          hold: 260,
        },
        {
          type: "reasoning",
          label: "Reasoning",
          text: "The display should normalize to the selected unit and treat missing rain as 0 mm. I will keep the UI unchanged and patch the parser boundary.",
          duration: 1150,
          hold: 240,
        },
        {
          type: "tool",
          name: "apply_patch",
          input:
            "src/weather/parser.ts\nsrc/weather/fixtures.ts\ntests/weather-parser.test.ts",
          result:
            "+ normalized provider units before display\n+ defaulted empty precipitation to 0 mm\n+ added fixtures for hot, cold and no-rain forecasts",
          duration: 1050,
          hold: 260,
        },
        {
          type: "tool",
          name: "npm test",
          input: "npm test -- weather-parser.test.ts",
          result: "12 passed in 0.84s",
          duration: 1100,
          hold: 300,
        },
        {
          type: "message",
          role: "assistant",
          label: "Codex",
          variant: "final",
          text: "Fixed the weather card by normalizing the parser output before it reaches the UI.",
          points: [
            "Phoenix now renders as 72°F instead of 72°C.",
            "Missing rain values display as 0 mm.",
            "Added fixture coverage for hot, cold and no-rain forecasts.",
          ],
          duration: 760,
          hold: 1350,
        },
        {
          type: "analysis",
          progress: 0.4,
          hold: 180,
        },
        {
          type: "phase",
          index: "03",
          label: "Recommendation",
          progress: 0.57,
          hold: 200,
        },
        {
          type: "screen",
          screen: "penelopa",
          hold: 1050,
        },
        {
          type: "scroll",
          target: 0.48,
          duration: 1900,
          hold: 720,
        },
        {
          type: "copy",
          duration: 820,
          hold: 850,
        },
        {
          type: "screen",
          screen: "agent",
          hold: 650,
        },
        {
          type: "phase",
          index: "04",
          label: "Applied",
          progress: 0.72,
          hold: 160,
        },
        {
          type: "compose",
          mode: "paste",
          text: "Apply this Penelopa recommendation to the repository:\n\n“Create a reusable weather data validation skill. Check units, missing temperatures, empty precipitation, timezone labels and API fixtures before changing weather UI code.”",
          duration: 520,
          hold: 380,
        },
        {
          type: "send",
          label: "You",
          hold: 540,
        },
        {
          type: "reasoning",
          label: "Reasoning",
          text: "I will turn the recommendation into repository-owned instructions plus a small fixture check, then cover it so future agents can trust it.",
          duration: 1050,
          hold: 250,
        },
        {
          type: "tool",
          name: "write_file",
          input:
            ".codex/skills/weather-data-validation/SKILL.md\nscripts/check_weather_data.ts\ntests/check-weather-data.test.ts",
          result:
            "Created the reusable workflow, deterministic fixture checks and test coverage.",
          duration: 1050,
          hold: 230,
        },
        {
          type: "tool",
          name: "run_checker",
          input: "npm run check:weather-data",
          result: "units        ok\nmissing temp ok\nrain fallback ok\ntimezone     ok",
          duration: 1050,
          hold: 230,
        },
        {
          type: "tool",
          name: "npm test",
          input: "npm test -- check-weather-data.test.ts weather-parser.test.ts",
          result: "18 passed in 1.12s",
          duration: 950,
          hold: 280,
        },
        {
          type: "message",
          role: "assistant",
          label: "Codex",
          variant: "final",
          text: "The weather validation workflow is now part of the repository.",
          points: [
            "Future sessions get the same weather data checklist up front.",
            "One command checks units, missing values and timezone labels.",
            "Tests protect the checker and the parser fix.",
          ],
          duration: 780,
          hold: 800,
        },
        {
          type: "complete",
          progress: 1,
        },
      ],
    },
    claude: {
      label: "Claude",
      mark: "✦",
      model: "Claude Code",
      composerPlaceholder: "Ask Claude to follow up",
      accentLight: "#9a5c43",
      accentDark: "#e0a084",
      flow: [
        {
          type: "phase",
          index: "01",
          label: "Session",
          progress: 0.03,
          hold: 250,
        },
        {
          type: "compose",
          mode: "type",
          text: "The forecast card mixes Celsius and Fahrenheit on some cities. Please investigate without widening the change.",
          duration: 1150,
          hold: 180,
        },
        {
          type: "send",
          label: "You",
          hold: 520,
        },
        {
          type: "reasoning",
          label: "Reasoning",
          text: "I will inspect the weather parser contract, compare the provider fixtures and keep the fix at the narrowest reliable boundary.",
          duration: 1000,
          hold: 250,
        },
        {
          type: "tool",
          name: "Grep",
          input: "pattern: temperature|unit|precipitation\npath: src/weather",
          result: "Matched parser.ts and fixtures.ts. Provider units are inconsistent across cities.",
          duration: 950,
          hold: 220,
        },
        {
          type: "tool",
          name: "Read",
          input: "src/weather/parser.ts lines 34-78",
          result: "The parser passes through provider values instead of normalizing them for the selected display unit.",
          duration: 900,
          hold: 250,
        },
        {
          type: "reasoning",
          label: "Reasoning",
          text: "This belongs at the parser boundary. I will normalize temperatures once, preserve the component API and add fixtures for the tricky cases.",
          duration: 1100,
          hold: 230,
        },
        {
          type: "tool",
          name: "Edit",
          input: "parser.ts + fixtures.ts + weather parser tests",
          result: "Added unit normalization, rain fallback handling and fixture coverage.",
          duration: 1050,
          hold: 250,
        },
        {
          type: "tool",
          name: "Bash",
          input: "npm test -- weather-parser.test.ts",
          result: "12 passed in 0.81s",
          duration: 1050,
          hold: 300,
        },
        {
          type: "message",
          role: "assistant",
          label: "Claude",
          variant: "final",
          text: "Resolved the mixed-unit weather bug at the parser boundary.",
          points: [
            "Forecast cards now receive one normalized display value.",
            "Missing rain is handled before rendering.",
            "Fixtures cover the cities that previously drifted.",
          ],
          duration: 760,
          hold: 1350,
        },
        {
          type: "analysis",
          progress: 0.4,
          hold: 180,
        },
        {
          type: "phase",
          index: "03",
          label: "Recommendation",
          progress: 0.57,
          hold: 200,
        },
        {
          type: "screen",
          screen: "penelopa",
          hold: 1050,
        },
        {
          type: "scroll",
          target: 0.48,
          duration: 1900,
          hold: 720,
        },
        {
          type: "copy",
          duration: 820,
          hold: 850,
        },
        {
          type: "screen",
          screen: "agent",
          hold: 650,
        },
        {
          type: "phase",
          index: "04",
          label: "Applied",
          progress: 0.72,
          hold: 160,
        },
        {
          type: "compose",
          mode: "paste",
          text: "Apply this Penelopa recommendation to the repository:\n\n“Create a reusable weather data validation skill. Check units, missing temperatures, empty precipitation, timezone labels and API fixtures before changing weather UI code.”",
          duration: 520,
          hold: 380,
        },
        {
          type: "send",
          label: "You",
          hold: 540,
        },
        {
          type: "reasoning",
          label: "Reasoning",
          text: "I will encode this as project memory plus a fixture checker, with focused tests so the workflow remains dependable across future sessions.",
          duration: 1050,
          hold: 250,
        },
        {
          type: "tool",
          name: "Write",
          input:
            ".claude/skills/weather-data-validation/SKILL.md\nscripts/check_weather_data.ts\ntests/check-weather-data.test.ts",
          result: "Created the skill, checker and test coverage.",
          duration: 1050,
          hold: 230,
        },
        {
          type: "tool",
          name: "Bash",
          input: "npm run check:weather-data",
          result: "units        ok\nmissing temp ok\nrain fallback ok\ntimezone     ok",
          duration: 1050,
          hold: 230,
        },
        {
          type: "tool",
          name: "Bash",
          input: "npm test -- check-weather-data.test.ts weather-parser.test.ts",
          result: "18 passed in 1.08s",
          duration: 950,
          hold: 280,
        },
        {
          type: "message",
          role: "assistant",
          label: "Claude",
          variant: "final",
          text: "Applied. Weather data validation is now a reusable project capability.",
          points: [
            "The skill explains when and how to run the weather checks.",
            "The script verifies units, missing values and timezone labels.",
            "The combined focused suite passes.",
          ],
          duration: 780,
          hold: 800,
        },
        {
          type: "complete",
          progress: 1,
        },
      ],
    },
  } satisfies Record<AgentKey, AgentConfig>,
};

export const TOKEN_POSITIONS = [
  ["6%", "14%", "-90px", "38px", "470px", "210px", "4.8s", "-0.2s"],
  ["72%", "11%", "110px", "20px", "-340px", "245px", "5.4s", "-1.7s"],
  ["3%", "44%", "-120px", "0px", "500px", "20px", "5.7s", "-2.4s"],
  ["78%", "48%", "130px", "-10px", "-400px", "0px", "4.6s", "-0.9s"],
  ["11%", "78%", "-70px", "90px", "430px", "-260px", "6.1s", "-3.4s"],
  ["69%", "79%", "90px", "100px", "-300px", "-270px", "5.1s", "-2.1s"],
  ["25%", "5%", "0px", "-80px", "180px", "280px", "4.9s", "-3.7s"],
  ["58%", "3%", "0px", "-90px", "-80px", "310px", "5.6s", "-1.2s"],
  ["19%", "57%", "-120px", "20px", "260px", "-40px", "4.3s", "-2.8s"],
  ["62%", "63%", "120px", "30px", "-180px", "-70px", "5.8s", "-4.2s"],
  ["38%", "91%", "-20px", "100px", "70px", "-320px", "5.2s", "-1.9s"],
  ["47%", "10%", "10px", "-100px", "0px", "250px", "4.7s", "-3.1s"],
] as const;

